#!groovy
properties([disableConcurrentBuilds()])

pipeline {
    agent any
    triggers { pollSCM('* * * * *') }
    options {
        timestamps()
    }
    stages {
        stage("checks") {
            steps {
                bat "docker-compose up --build -d checks"
            }
        }
        
      stage("docker login") {
            steps {
                bat "docker login"
            }
        }

        stage("docker build") {
            steps {
                bat "docker-compose build"
                bat "docker tag audioplayer-app n1ktrnv/audioplayer:latest"
            }
        }

        stage("docker push") {
            steps {
                bat "docker push n1ktrnv/audioplayer"
            }
        }
    }
}
