#!groovy
properties([disableConcurrentBuilds()])

pipeline {
    agent any
    triggers { pollSCM('* * * * *') }
    options {
        timestamps()
    }
    stages {
        stage("checks") {
            steps {
                echo " ============== checks =================="
                bat "docker-compose up --build checks"
                bat "docker compose rm checks -f"
            }
        }
    }
}